<a href="https://colab.research.google.com/github/filiptomczak/colab/blob/main/supervised/01_basic/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nowa sekcja

# Nowa sekcja

In [3]:
import sklearn
import numpy as np
import pandas as pd

In [4]:
data={
    'size':['xl','l','m','l','m'],
    'color':['red','green','blue','green','red'],
    'gender':['female','male','male','female','female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw=pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   xl    red  female  199.0     500    yes
1    l  green    male   89.0     450     no
2    m   blue    male   99.0     300    yes
3    l  green  female  129.0     380     no
4    m    red  female   79.0     410    yes

In [5]:
df=df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


In [6]:
for col in ['size','color','gender','bought']:
  df[col]=df[col].astype('category')

df['weight']=df['weight'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes


In [7]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [8]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       l    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

mapowanie wartosci [yes,no] kolumny bought na [1,0]

In [9]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [10]:
df['bought'] = le.fit_transform(df['bought'])

df

size  color  gender  price  weight  bought
0   xl    red  female  199.0   500.0       1
1    l  green    male   89.0   450.0       0
2    m   blue    male   99.0   300.0       1
3    l  green  female  129.0   380.0       0
4    m    red  female   79.0   410.0       1

In [11]:
df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   xl    red  female  199.0   500.0    yes
1    l  green    male   89.0   450.0     no
2    m   blue    male   99.0   300.0    yes
3    l  green  female  129.0   380.0     no
4    m    red  female   79.0   410.0    yes

In [16]:
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [17]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [18]:
encoder.categories_

[array(['l', 'm', 'xl'], dtype=object)]

In [20]:
encoder=OneHotEncoder(drop='first',sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [21]:
pd.get_dummies(data=df)

price  weight  size_l  size_m  size_xl  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True

In [22]:
pd.get_dummies(data=df,drop_first=True)

price  weight  size_m  size_xl  color_green  color_red  gender_male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [25]:
pd.get_dummies(data=df,drop_first=True,prefix='new',prefix_sep='-')

price  weight  new-m  new-xl  new-green  new-red  new-male  new-yes
0  199.0   500.0  False    True      False     True     False     True
1   89.0   450.0  False   False       True    False      True    False
2   99.0   300.0   True   False      False    False      True     True
3  129.0   380.0  False   False       True    False     False    False
4   79.0   410.0   True   False      False     True     False     True

In [26]:
pd.get_dummies(data=df,drop_first=True,prefix='new',prefix_sep='-',columns=['size'])

color  gender  price  weight bought  new-m  new-xl
0    red  female  199.0   500.0    yes  False    True
1  green    male   89.0   450.0     no  False   False
2   blue    male   99.0   300.0    yes   True   False
3  green  female  129.0   380.0     no  False   False
4    red  female   79.0   410.0    yes   True   False

In [27]:
print(f"{df['price']}\n")
print(f"srednia {df['price'].mean()}\n")
print(f"odchylenie standardowe {df['price'].std():.4f}\n")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

srednia 119.0

odchylenie standardowe 48.4768



In [28]:
(df['price']-df['price'].mean())/df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [29]:
def standardize(x):
  return (x-x.mean())/x.std()

standardize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [32]:
from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [33]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [43]:
scaler=StandardScaler()
df[['price','weight']]=scaler.fit_transform(df[['price','weight']])

df

size  color  gender     price    weight bought
0   xl    red  female  1.845062  1.366002    yes
1    l  green    male -0.691898  0.623610     no
2    m   blue    male -0.461266 -1.603567    yes
3    l  green  female  0.230633 -0.415740     no
4    m    red  female -0.922531  0.029696    yes

In [44]:
df2=df_raw.copy()

df2

size  color  gender  price  weight bought
0   xl    red  female  199.0     500    yes
1    l  green    male   89.0     450     no
2    m   blue    male   99.0     300    yes
3    l  green  female  129.0     380     no
4    m    red  female   79.0     410    yes

In [61]:
le=LabelEncoder()
df2['bought']=le.fit_transform(df['bought'])

scaler=StandardScaler()
df2[['price','weight']]=scaler.fit_transform(df[['price','weight']])

df2

size_m  size_xl  color_green  color_red  gender_male  bought     price  \
0       0        1            0          1            0       1  1.845062   
1       0        0            1          0            1       0 -0.691898   
2       1        0            0          0            1       1 -0.461266   
3       0        0            1          0            0       0  0.230633   
4       1        0            0          1            0       1 -0.922531   

     weight  
0  1.366002  
1  0.623610  
2 -1.603567  
3 -0.415740  
4  0.029696

In [62]:
df2=pd.get_dummies(data=df2,drop_first=True)
df2

size_m  size_xl  color_green  color_red  gender_male  bought     price  \
0       0        1            0          1            0       1  1.845062   
1       0        0            1          0            1       0 -0.691898   
2       1        0            0          0            1       1 -0.461266   
3       0        0            1          0            0       0  0.230633   
4       1        0            0          1            0       1 -0.922531   

     weight  
0  1.366002  
1  0.623610  
2 -1.603567  
3 -0.415740  
4  0.029696