<a href="https://colab.research.google.com/github/filiptomczak/colab/blob/main/intro/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
x=np.array([1,3])
print(x)

[1 3]


In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x=np.array([[1,2],[3,4]] )

In [9]:
x.shape

(2, 2)

In [10]:
y=x

z=x+y
z

array([[2, 4],
       [6, 8]])

In [11]:
x=np.array([[1,2,3],[3,2,1]])
x.shape

(2, 3)

In [12]:
x=np.array(
    [[[4,3,1],
      [3,2,1]],

     [[1,2,3],
      [1,2,3]],

     [[1,2,3],
      [1,2,3]]]
)

x.shape

(3, 2, 3)

In [13]:
A=np.array([1,2,3],dtype='float')
A.dtype

dtype('float64')

In [14]:
A=np.array([1.1,2.6,3.9],dtype='int')
A

array([1, 2, 3])

In [15]:
np.zeros(shape=(4,10),dtype='int8')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [16]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.full(shape=(3,3),fill_value=5,dtype='int8')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int8)

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(start=5,stop=20,step=5)

array([ 5, 10, 15])

In [20]:
np.linspace(start=0,stop=10,num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
A=np.arange(15)
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
A=np.array([1,2,3,4])
B=np.array([4,3,2,1])

print(A)
print(B)

C=A*B-4
print(C)

[1 2 3 4]
[4 3 2 1]
[0 2 2 0]


In [23]:
np.add(A,B)
np.subtract(A,B)
np.multiply(A,B)
np.divide(A,B)

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [24]:
X=np.array([[1,2],[2,3]])
Y=np.array([[2,1],[3,2]])

print(X)
print(Y)

[[1 2]
 [2 3]]
[[2 1]
 [3 2]]


In [25]:
Z=X*Y
Z

array([[2, 2],
       [6, 6]])

In [26]:
Z=np.dot(X,Y)
Z

array([[ 8,  5],
       [13,  8]])

In [27]:
Z=np.dot(Y,X)
Z

array([[ 4,  7],
       [ 7, 12]])

In [28]:
np.random.seed(0)

np.random.randn(3,3)

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [29]:
np.random.randint(10,size=(3,3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [30]:
a=np.array([1,2,3,4])
z=np.random.choice([1,2,34])
z

np.int64(1)

In [31]:
np.random.choice(['python','sql','c#'])

np.str_('python')

In [32]:
data=np.arange(10)
np.random.shuffle(data)
data

array([4, 8, 1, 7, 9, 2, 0, 6, 5, 3])

In [33]:
np.exp(1)

np.float64(2.718281828459045)

In [34]:
np.sqrt(2)

np.float64(1.4142135623730951)

In [35]:
np.all([2,3,4,0])

np.False_

In [36]:
np.any([1,0,0])

np.True_

In [37]:
A=np.random.rand(5)
A

array([0.52047748, 0.67887953, 0.72063265, 0.58201979, 0.53737323])

In [38]:
A[np.argmax(A)]

np.float64(0.7206326547259168)

In [39]:
A[np.argmin(A)]

np.float64(0.5204774795512048)

In [40]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
B=A[2:10]
B

array([2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
c=A.reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
d=c[1:2,3:3]
print(d)

[]


In [45]:
A=np.arange(20)
A.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
A=A.reshape(4,5)

for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [53]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [55]:
A.ravel()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
A=np.arange(start=-10,stop=10,step=0.5)
A=A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [60]:
mask=A>0
mask

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [63]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [64]:
np.bitwise_or(A<-5,A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])