<a href="https://colab.research.google.com/github/filiptomczak/colab/blob/main/intro/statystyka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [23]:
v1=np.array([0,4])
v1


array([0, 4])

In [24]:
np.linalg.norm(v1)

np.float64(4.0)

In [25]:
v2=np.array([-1,10,13])
np.linalg.norm(v2)

np.float64(16.431676725154983)

In [26]:
p1=np.array([3,4])
p2=np.array([5,6])


np.linalg.norm(p1-p2)

np.float64(2.8284271247461903)

In [27]:
p1=np.array([3,4,0])
p2=np.array([5,6,2 ])


np.linalg.norm(p1-p2)

np.float64(3.4641016151377544)

In [28]:
A=np.array([[3,1,3],[1,6,3],[1,2,3]])
round(np.linalg.det(A))

24

slad macierzy - suma elementow na glownej przekatnej

In [29]:
np.trace(A)

np.int64(12)

In [30]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
A=np.array([[1,2],[3,4]])

In [32]:
B=np.linalg.inv(A)
B
np.set_printoptions(precision=2,suppress=True)
A.dot(B)

array([[1., 0.],
       [0., 1.]])

In [33]:
A.T

array([[1, 3],
       [2, 4]])

In [34]:
A=np.array([[2,4],[1,-1]])
B=np.array([[10],[-1]])

X=np.linalg.inv(A).dot(B)
X

array([[1.],
       [2.]])

In [36]:
price=np.arange(15)
price=price.reshape(3,5)
price

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
price.sum()

np.int64(105)

In [40]:
price.sum(axis=0)

array([15, 18, 21, 24, 27])

In [41]:
np.min(price)

np.int64(0)

In [42]:
np.max(price)

np.int64(14)

In [43]:
np.median(price)

np.float64(7.0)

In [45]:
np.mean(price,axis=0)

array([5., 6., 7., 8., 9.])

In [47]:
np.std(price,axis=1)

array([1.41, 1.41, 1.41])

In [48]:
np.var(price)

np.float64(18.666666666666668)

In [49]:
price.ndim

2

In [51]:
np.array([True,1,2.0])

array([1., 1., 2.])